import { getTrackerData } from "@/lib/kv";
import SwimlaneDiagram from "@/components/SwimlaneDiagram";

export const revalidate = 60;

export default async function FlowsPage() {
  const data = await getTrackerData();
  const flows = data.domain_flows;

  return (
    <div className="mx-auto max-w-6xl space-y-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Flows</h1>
        <p className="mt-1 text-sm text-text-dim">
          Cross-domain data flows showing how concepts connect across your stack.
        </p>
      </div>

      {flows && flows.length > 0 ? (
        <SwimlaneDiagram flows={flows} />
      ) : (
        <div className="rounded-2xl border border-border bg-surface p-12 text-center">
          <div className="text-3xl mb-3">🔀</div>
          <h2 className="text-lg font-semibold mb-2">No Flow Data Yet</h2>
          <p className="text-sm text-text-dim max-w-md mx-auto">
            Domain flows are generated by the{" "}
            <code className="bg-surface2 px-1 rounded">
              weekly-learning-tracker
            </code>{" "}
            skill. Run the skill to populate this page with cross-domain
            flows.
          </p>
          <p className="mt-3 text-xs text-text-dim">
            Add <code className="bg-surface2 px-1 rounded">domain_flows</code>{" "}
            to your tracker data to visualize how concepts flow across
            Frontend, Backend, Infra, and AI domains.
          </p>
        </div>
      )}
    </div>
  );
}
