import { getTrackerData, getArchitecture } from "@/lib/kv";
import ArchitectureTree from "@/components/ArchitectureTree";

export const revalidate = 60;

export default async function ArchitecturePage() {
  const [data, tree] = await Promise.all([
    getTrackerData(),
    getArchitecture(),
  ]);

  return (
    <div className="mx-auto max-w-4xl space-y-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Architecture</h1>
        <p className="mt-1 text-sm text-text-dim">
          Interactive drill-down from system to function. Explore the codebase structure.
        </p>
      </div>

      {tree ? (
        <ArchitectureTree tree={tree} concepts={data.concepts} />
      ) : (
        <div className="rounded-2xl border border-border bg-surface p-12 text-center">
          <div className="text-3xl mb-3">🏗️</div>
          <h2 className="text-lg font-semibold mb-2">No Architecture Data Yet</h2>
          <p className="text-sm text-text-dim max-w-md mx-auto">
            Architecture data is generated by the <code className="bg-surface2 px-1 rounded">weekly-learning-tracker</code> skill.
            Run the skill to populate this page with your project&apos;s structure.
          </p>
          <p className="mt-3 text-xs text-text-dim">
            Data is stored in KV key <code className="bg-surface2 px-1 rounded">tracker:architecture</code> or local file <code className="bg-surface2 px-1 rounded">data/architecture.json</code>.
          </p>
        </div>
      )}
    </div>
  );
}
